name: Add Merged PR Author to Contributors

on:
  pull_request:
    types:
      - closed
jobs:
  add-contributor:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Debug
        run: |
          if [ -n "${{ secrets.ACTION_TOKEN }}" ]; then
            echo "ACTION_TOKEN is set"
          else
            echo "ACTION_TOKEN is not set"
          fi
          
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Get PR author
        id: get_author
        run: |
          echo "author=${{ github.event.pull_request.user.login }}" >> $GITHUB_OUTPUT

      - name: Check if author is already in CONTRIBUTORS.md
        id: check_contributor
        run: |
          AUTHOR="@${{ steps.get_author.outputs.author }}"
          if grep -q "$AUTHOR" CONTRIBUTORS.md; then
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
          fi

      - name: Add author to CONTRIBUTORS.md
        if: steps.check_contributor.outputs.found == 'false'
        run: |
          AUTHOR="${{ steps.get_author.outputs.author }}"
          echo "- [@$AUTHOR](https://github.com/$AUTHOR)" >> CONTRIBUTORS.md

      - name: Commit and push changes
        if: steps.check_contributor.outputs.found == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add CONTRIBUTORS.md
          git commit -m "Add @${{ steps.get_author.outputs.author }} to CONTRIBUTORS.md"
          git push
