name: Auto-update Contributors

on:
  # Trigger action on pull request closed
  pull_request:
    types: [closed]
    # List of branches to work on
    branches:
      - main
      - master

env:
  GIT_USER_EMAIL:     "nirgeier@gmail.com"
  GIT_USER_NAME:      "Nir Geier"
  PR_AUTHOR:          "nirgeier"

jobs:
  add-contributor:

    # Only run this job when a PR is merged (not just closed)
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
        with:
          # Full git history needed to get proper commit info
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.ACTION_TOKEN }}
        
      - name: Add contributor if not exists
        id: check_contributor
        run: |
          touch CONTRIBUTORS.md
          # Check if author already exists in the file
          if grep -q "${{ env.PR_AUTHOR }}" CONTRIBUTORS.md; 
          then
            echo "Author ${{ env.PR_AUTHOR }} already exists in CONTRIBUTORS.md"
          else
            PR_AUTHOR="${{ github.event.pull_request.user.login }}"
            echo "Adding contributor [${{ env.PR_AUTHOR }}] to CONTRIBUTORS.md"
            echo "- [@${{ env.PR_AUTHOR }}](https://github.com/${{ env.PR_AUTHOR }})" >> CONTRIBUTORS.md
          fi
        
      - name: Commit and push changes
        if: env.CONTRIBUTOR_EXISTS == 'false'
        run: |
          git config --local user.email ${{ env.GIT_USER_EMAIL }}
          git config --local user.name ${{ env.GIT_USER_NAME }}
          git add .
          git commit -m "Automatically added @${{ env.PR_AUTHOR }} to contributors by GitHub Action after PR merge"
          git push
